name: Apply alerts

on:
  push:
    branches:
      - main
    paths:
      - 'apply-alerts.yml'
      - 'alerts/**'

jobs:
  apply-alerts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: nais/deploy/actions/deploy@v3
        env:
          CLUSTER: prod-gcp
          RESOURCE: alerts/alert-manager-config.yaml,alerts/alerts.yaml
