name: Build and deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@v7 # Should be pinned (1)
      - name: Build application jar
        run: ./gradlew --no-daemon jar
      - name: Build and push image and SBOM to OCI registry
        uses: nais/docker-build-push@v0 # Should be pinned
        id: docker-build-push
        with:
          team: ufore

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7 # Should be pinned
      - uses: nais/setup@v1 # Should be pinned
        with:
          team: ufore
      - name: Deploy to Nais
        run: |
          # Select the Nais environment. (2)
          nais apply .nais/app.yaml \
            --environment <MY-ENV> \
            --set spec.image="${{ needs.build.outputs.image }}" \
            --wait
